# Generated automatically from Makefile.ecbilt.inputdata.in by configure.
# 
#	$Id: Makefile.ecbilt.inputdata.in,v 1.1.2.1 2001/05/28 15:17:01 severijn Exp $
#

srcdir		= .

top_srcdir	= ../..

subdirs		= artiforc lwrpar swrpar

include ../../config/make.macros


EXTRACFLAGS	=
EXTRACPPFLAGS	=
EXTRAFFLAGS	=
EXTRALDFLAGS	=
EXTRALIBS	=


distfiles= \
	berg.asc	\
	berg.dat	\
	coef.asc	\
	coef.dat	\
	gauss.asc

dist_garbage = \
	Makefile

garbage =

more_garbage =


include ../../config/make.rules


run: subdir_run

depend:	subdir_depend

install: subdir_install

install-strip: subdir_install-strip

main: subdir_main

uninstall: subdir_uninstall
