# Generated automatically from Makefile.ecbilt.inputdata.swrpar.in by configure.
# 
#	$Id: Makefile.ecbilt.inputdata.swrpar.in,v 1.1.2.2 2001/05/29 09:19:57 severijn Exp $
#

srcdir		= .

top_srcdir	= ../../..


include ../../../config/make.macros


EXTRACFLAGS	=
EXTRACPPFLAGS	=
EXTRAFFLAGS	=
EXTRALDFLAGS	=
EXTRALIBS	=


distfiles= \
	README		\
	cost_ref	\
	dfclrdcost	\
	dfclrdrs1	\
	dfuocdcost	\
	dfuocdrs	\
	fclrref		\
	fuocref		\
	salb_ref	\
	swrcoef.dat	\
	swrref.dat	\
	write.f

dist_garbage = \
	Makefile

garbage =

more_garbage =


include ../../../config/make.rules


run: subdir_run

depend:	subdir_depend

install: subdir_install

install-strip: subdir_install-strip

main: subdir_main

uninstall: subdir_uninstall
